#!/usr/bin/bash

if [ -z $AMPS_DEP_MODE ]; then
    echo "AMPS deployment mode not defined."
    exit 1
elif [ -z $AMPS_LOC ]; then
    echo "AMPS repo location not defined."
    exit 1
fi

pushd "$AMPS_LOC/scripts/deploy/commands"

# Parse flags
for arg; do
    if [[ $arg == '-'* ]]; then
        case $arg in
        "-g" | "--git")
            export AMPS_CLI_GIT="true"
            ;;
        "-e" | "--email")
            export AMPS_CLI_EMAIL="true"
            ;;
        esac
    fi
done

# Handle actual commands
case $1 in
"start")
    echo "starting AMPS..."
    ./start.sh
    ;;
"stop")
    echo "stoping AMPS..."
    ./stop.sh
    ;;
"pull")
    echo "pulling AMPS..."
    ./pull.sh
    ;;
*)
    echo "unrecognized command: '$1'"
    exit 1
    ;;
esac

popd
