import { Stage } from "@prisma/client";

// TODO: names pending
export const CHAPTER = {
  PRE_PUBLICATION: {
    SETUP: Stage.SETUP,
    PROJECT_SUBMISSION: Stage.PROJECT_SUBMISSION,
    PROJECT_SELECTION: Stage.PROJECT_SELECTION,
    ADJUSTING_PROJECT_ALLOCATION: Stage.ALLOCATION_ADJUSTMENT,
    ALLOCATION_PUBLICATION: Stage.ALLOCATION_PUBLICATION,
  },
  PUBLICATION: {
    READER_BIDDING: Stage.READER_BIDDING,
    READER_ALLOCATION: Stage.READER_ALLOCATION,
    MARKING: Stage.MARKING,
    FINAL_GRADES_RELEASED: Stage.FINAL_GRADES_RELEASED,
  },
};
